name: iOS Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app
          xcodebuild -version
          echo "Available SDKs:"
          xcodebuild -showsdks

      - name: List workspace
        run: |
          pwd
          ls -la
          echo "Looking for Xcode project files:"
          find . -name "*.xcodeproj" -o -name "*.xcworkspace"

      - name: Build
        run: |
          xcodebuild clean build \
            -project ChargeLimiter.xcodeproj \
            -scheme ChargeLimiter \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -verbose

      - name: Build Widget Extension
        run: |
          xcodebuild clean build \
            -project ChargeLimiter.xcodeproj \
            -scheme ChargeLimiterWidget \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            -verbose

      - name: List build directory
        run: |
          echo "Build directory contents:"
          ls -R build/

      - name: Create TIPA
        run: |
          mkdir -p Payload
          cp -rv build/Release-iphoneos/ChargeLimiter.app Payload/
          zip -r ChargeLimiter.tipa Payload
          rm -rf Payload
          ls -l ChargeLimiter.tipa

      - name: Create DEB
        run: |
          mkdir -p Package_rootless/Applications
          cp -rv build/Release-iphoneos/ChargeLimiter.app Package_rootless/Applications/
          cd Package_rootless
          find . -name '.DS_Store' -delete
          find . -type f -exec md5sum {} \; > DEBIAN/md5sums
          cd ..
          dpkg-deb -b Package_rootless ChargeLimiter.deb
          ls -l ChargeLimiter.deb

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ChargeLimiter.tipa
            ChargeLimiter.deb
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Automated build from GitHub Actions
            - Build number: ${{ github.run_number }}
            - Commit: ${{ github.sha }}

            ## 安装说明

            ### TIPA 安装
            1. 下载 ChargeLimiter.tipa
            2. 使用 AltStore 或其他签名工具安装

            ### DEB 安装
            1. 下载 ChargeLimiter.deb
            2. 使用 Filza 或其他包管理器安装
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
